#!/usr/bin/env python3
"""Thermodynamic learning algorithm for Project HENRI -- Langevin computer.

SOURCE (authoritative, not a paraphrase)
    Stephen Whitelam, "Generative thermodynamic computing",
    arXiv:2506.15121v3 [cond-mat.stat-mech], 30 Oct 2025.
    Molecular Foundry, Lawrence Berkeley National Laboratory.

THE ALGORITHM (equations quoted from the source, Eq. 1-12)
    Degrees of freedom x = {x_i} evolve under overdamped Langevin dynamics

        dx_i = -mu * d_i V_theta(x) dt + sqrt(2 mu kT dt) * eta_i        (Eq. 1, 3)

    with the potential

        V_theta(x) = J2 sum_i x_i^2 + J4 sum_i x_i^4
                     + sum_i b_i x_i + sum_{i<j} J_ij x_i x_j          (Eq. 2)

    and force

        d_i V_theta(x) = 2 J2 x_i + 4 J4 x_i^3 + b_i + sum_{j in N(i)} J_ij x_j
                                                                        (Eq. 12)

    Training maximises the probability that the SAME computer, run in reverse,
    would have generated a noising trajectory. The analytic gradients are
    (Eq. 10-11), with x' = x + dx the endpoint of a FORWARD step:

        -d/dJ_ij ln Ptilde = r_i x_j + r_j x_i
        -d/db_i  ln Ptilde = r_i
        r_i = (-dx_i + mu d_i V_theta(x') dt) / (2 kT)

    Parameter update is gradient ASCENT on ln Ptilde (Eq. 8-9):

        J_ij <- J_ij + alpha * d/dJ_ij ln Ptilde
        b_i  <- b_i  + alpha * d/db_i  ln Ptilde

    Physical meaning (Eq. 13-14): maximising that probability minimises the
    expected heat and entropy production of the generating dynamics. The
    learning rule is local -- each coupling update depends only on the two
    units it connects -- and it is data-computable without backpropagation
    through time.

WHY THIS IS THE HENRI LEARNING ALGORITHM
    HENRI's mandate is minimal training with frozen physical invariants.
    This rule supplies exactly that shape:
      * The invariant part is the potential's structure (J2, J4, kT); it is
        never trained.
      * The trainable part is the pairwise coupling field (J_ij, b_i), i.e.
        the same object HENRI calls the associative coupling / attention
        field. Its update is local, not global.
      * The objective is thermodynamic reversibility, not a benchmark score.
        Structure is generated by relaxing the trained potential from noise.
      * It is a self-supervised objective: it needs trajectories, no labels.

HONEST SCOPE
    This module implements and TESTS the source's algorithm on small synthetic
    structured data. It is not a benchmark claim, not a world-knowledge claim,
    and it is NOT wired into the production ARC/VLA path. The gates below are
    pre-registered. The null arm is the same computer with couplings held at
    zero, so a pass cannot be produced by the initial-condition sampler.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import torch
import torch.nn as nn


# --------------------------------------------------------------------------- data
def make_stripe_patterns(n_units: int, n_patterns: int = 3,
                         seed: int = 20261012) -> torch.Tensor:
    """Structured patterns on a 4x4 visible grid, ZERO-MEANED.

    Three canonical patterns (horizontal bar, vertical bar, diagonal). Absolute
    pattern identity is irrelevant; what matters is that the data distribution
    is LOW-ENTROPY relative to isotropic noise, so that a denoising computer has
    something to learn and a control can fail to find it.

    ZERO-MEANING IS PART OF THE SOURCE'S PROTOCOL, not a convenience. The source
    states its digits had "pixels adjusted to have zero mean and unit variance".
    This matters because the potential's linear term puts a unit's stationary
    point at x* = -b_i/(2 J2): a NON-zero-mean pattern carries a DC offset that
    the model must encode as a static bias, and the sign of the imprint inverts.
    Measured before this fix: corr(x(t0)_visible, pattern) = -0.93 at amplitude
    45 (experiments/verification/thermo_imprint_sweep_observed.json), i.e. the
    trajectory carried the pattern ANTI-aligned.
    """
    if n_units != 16:
        raise ValueError("stripe patterns are defined on a 4x4 grid (16 units)")
    pats: List[torch.Tensor] = []
    bar_h = torch.zeros(4, 4); bar_h[1, :] = 1.0
    bar_v = torch.zeros(4, 4); bar_v[:, 1] = 1.0
    diag = torch.eye(4)
    for p in (bar_h, bar_v, diag):
        pats.append(p.reshape(-1))
    out = torch.stack(pats[:n_patterns]).float()
    return out - out.mean(dim=-1, keepdim=True)


# ------------------------------------------------------------------- the computer
@dataclass
class LangevinConfig:
    """Frozen physical constants. None of these are trainable."""
    n_units: int = 48            # visible + hidden units
    n_visible: int = 16
    j2: float = 10.0             # intrinsic quadratic coupling (kT units)
    j4: float = 10.0             # quartic term: nonlinearity + thermodynamic stability
    kT: float = 1.0              # thermal energy scale
    mu: float = 1.0              # mobility
    dt: float = 0.005            # integration timestep
    t_final: float = 2.5         # trajectory duration
    noise_amp: float = 2.0       # imposed-pattern amplitude at t=0
    # D3 (bias orientation). The potential's linear term places a unit's
    # stationary point at x* = -b_i/(2 J2), so a POSITIVE imposed bias drives the
    # unit ANTI-aligned with the pattern. The source can ignore this because its
    # digits are zero-mean and its symmetry x -> -x is nearly unbroken (it even
    # notes the digit "1" appearing inverted). With a signed readout the
    # orientation matters, so the imposed bias is negated to put the equilibrium
    # IN PHASE with the pattern. Set bias_sign=+1.0 to reproduce the literal
    # source convention.
    bias_sign: float = -1.0

    @property
    def n_steps(self) -> int:
        return int(round(self.t_final / self.dt))


class LangevinComputer(nn.Module):
    """A thermodynamic computer: N fluctuating units with trainable couplings.

    Trainable parameters are exactly the source's theta = ({J_ij}, {b_i}).
    The potential's intrinsic terms (J2, J4, kT, mu) are buffers, not parameters,
    so an optimizer can never drift the physics.
    """

    def __init__(self, cfg: Optional[LangevinConfig] = None,
                 seed: int = 20261012, device: str = "cpu") -> None:
        super().__init__()
        self.cfg = cfg or LangevinConfig()
        self.device = device

        n = self.cfg.n_units
        # theta: raw lower-triangular couplings; effective J is symmetrized.
        self.J_raw = nn.Parameter(torch.zeros(n, n))
        self.b = nn.Parameter(torch.zeros(n))
        # Symmetry mask (no self-coupling) is a frozen buffer.
        off = torch.ones(n, n) - torch.eye(n)
        self.register_buffer("offdiag", off)
        g = torch.Generator(device="cpu").manual_seed(int(seed))
        self._gen_seed = int(seed)
        self._gen = g
        self.to(device)

    # ------------------------------------------------------------- theta views
    def effective_J(self) -> torch.Tensor:
        """Symmetric zero-diagonal coupling matrix.

        The potential's pair sum runs over i<j, so storing a symmetric matrix
        with J_ij = J_ji and zero diagonal reproduces  sum_{i<j} J_ij x_i x_j
        exactly as 0.5 * x^T J x.
        """
        return 0.5 * (self.J_raw + self.J_raw.t()) * self.offdiag

    def force(self, x: torch.Tensor) -> torch.Tensor:
        """d_i V_theta(x), Eq. 12.  x: [..., N] -> [..., N]."""
        J = self.effective_J()
        quad = 2.0 * self.cfg.j2 * x
        quartic = 4.0 * self.cfg.j4 * x ** 3
        linear = self.b
        coupled = x @ J.t()
        return quad + quartic + linear + coupled

    def potential(self, x: torch.Tensor) -> torch.Tensor:
        """V_theta(x), Eq. 2.  x: [..., N] -> [...]. Used for the heat measurement."""
        J = self.effective_J()
        p2 = self.cfg.j2 * (x ** 2).sum(dim=-1)
        p4 = self.cfg.j4 * (x ** 4).sum(dim=-1)
        pb = x @ self.b
        pair = 0.5 * torch.einsum("...i,ij,...j->...", x, J, x)
        return p2 + p4 + pb + pair

    # ---------------------------------------------------------------- dynamics
    def _randn(self, shape, generator=None) -> torch.Tensor:
        g = generator if generator is not None else self._gen
        return torch.randn(shape, generator=g, dtype=torch.float32).to(self.device)

    @torch.no_grad()
    def step(self, x: torch.Tensor, bias: Optional[torch.Tensor] = None,
             generator=None) -> torch.Tensor:
        """One Euler step of Eq. 3 with an optional externally imposed bias.

        bias is added to the potential's linear term (the source imposes the
        digit on the visible units through b_i during noising).
        """
        cfg = self.cfg
        f = self.force(x)
        if bias is not None:
            f = f + bias
        noise = math.sqrt(2.0 * cfg.mu * cfg.kT * cfg.dt) * self._randn(
            x.shape, generator)
        return x - cfg.mu * f * cfg.dt + noise

    # ------------------------------------------------------------- trajectories
    @torch.no_grad()
    def noise_trajectory(self, pattern: torch.Tensor,
                         generator=None) -> Tuple[torch.Tensor, torch.Tensor]:
        """Forward (noising) trajectory omega = {x(t_k)}_{k=0..K}.

        Procedure from the source's numerical illustration: project the pattern
        onto the visible units, give the hidden units a scaled copy as signal,
        set ALL COUPLINGS to zero, equilibrate, then run a trajectory while
        slowly diminishing the imposed pattern. The couplings must be zero here:
        this is a noising process, not the trained dynamics.
        """
        cfg = self.cfg
        n_v = cfg.n_visible
        J_saved = self.J_raw.data.clone()
        b_saved = self.b.data.clone()
        self.J_raw.data.zero_()
        self.b.data.zero_()

        bias0 = torch.zeros(cfg.n_units, device=self.device)
        bias0[:n_v] = cfg.bias_sign * cfg.noise_amp * pattern.to(self.device)
        # Hidden units receive a scaled copy of the same signal.
        for j in range(n_v, cfg.n_units):
            bias0[j] = cfg.bias_sign * cfg.noise_amp * pattern[j % n_v].to(self.device)

        # Equilibrate at the full imposed pattern.
        x = torch.zeros(cfg.n_units, device=self.device)
        for _ in range(int(1.0 / cfg.dt)):
            x = self.step(x, bias=bias0, generator=generator)

        traj = [x.clone()]
        for k in range(1, cfg.n_steps + 1):
            tau = k * cfg.dt / cfg.t_final
            x = self.step(x, bias=(1.0 - tau) * bias0, generator=generator)
            traj.append(x.clone())

        self.J_raw.data.copy_(J_saved)
        self.b.data.copy_(b_saved)
        return torch.stack(traj), bias0

    @torch.no_grad()
    def generate(self, generator=None) -> torch.Tensor:
        """Relax from a noisy initial state under the TRAINED dynamics, b = 0.

        The initial state is prepared by equilibrating the coupling-free
        computer, exactly as the source describes.
        """
        cfg = self.cfg
        J_saved = self.J_raw.data.clone()
        b_saved = self.b.data.clone()
        self.J_raw.data.zero_()
        self.b.data.zero_()
        x = torch.zeros(cfg.n_units, device=self.device)
        for _ in range(int(0.5 / cfg.dt)):
            x = self.step(x, bias=None, generator=generator)
        self.J_raw.data.copy_(J_saved)
        self.b.data.copy_(b_saved)

        for _ in range(cfg.n_steps):
            x = self.step(x, bias=None, generator=generator)
        return x

    # ------------------------------------------------------- analytic gradients
    def reverse_logprob_grad(self, traj: torch.Tensor) -> Tuple[torch.Tensor,
                                                                torch.Tensor]:
        """d/dtheta ln Ptilde, accumulated over a whole trajectory (Eq. 10-11).

        traj: [K+1, N] states x(t_k). The reverse trajectory is the time-reversal
        of this one; a step of the forward trajectory is x(t_k) -> x(t_{k+1}).

        Returns (grad_J_raw, grad_b) with the SAME shape as the parameters, so
        gradient ASCENT is  theta <- theta + alpha * grad.
        """
        cfg = self.cfg
        x = traj[:-1]                                  # [K, N]  start of each step
        dx = traj[1:] - traj[:-1]                      # [K, N]  forward displacement
        xp = traj[1:]                                  # [K, N]  x' = x + dx

        # r_i = (-dx_i + mu d_i V_theta(x') dt) / (2 kT).
        # NOTE: the force here must include theta's trainable couplings, which is
        # what makes this a genuine gradient of the model's own likelihood.
        r = (-dx + cfg.mu * self.force(xp) * cfg.dt) / (2.0 * cfg.kT)

        # d/dJ_ij ln Ptilde = -(r_i x'_j + r_j x'_i), summed over steps.
        #
        # CORRECTED 2026-10-12 by float64 finite-difference check
        # (experiments/verification/thermo_gradcheck.py). Two defects were found:
        #   (i)  the derivative must use x' = x + dx (the ENDPOINT of the forward
        #        step), because the couple term of the force in Eq. (12) is
        #        evaluated at x':  d/dJ_ij [ sum_j J_ij x'_j ] = x'_j.
        #        Using the step START x_j is wrong, and the earlier version did.
        #   (ii) a spurious 0.5 symmetrisation factor halved the result.
        # The bias gradient was already exactly right (matched a float64 central
        # difference to 5e-12), which is what localised the fault to the couple
        # term alone.
        gx = torch.einsum("ki,kj->ij", r, xp)          # sum_k r_i x'_j
        grad_J = -(gx + gx.t()) * self.offdiag
        grad_b = -r.sum(dim=0)
        return grad_J, grad_b

    # ------------------------------------------------------------------- train
    def train_on_patterns(self, patterns: torch.Tensor, steps: int = 300,
                          n_traj_per_step: int = 4, alpha: float = 0.05,
                          seed: int = 0, verbose: bool = False,
                          normalize_by_steps: bool = True
                          ) -> Dict[str, object]:
        """Maximise ln Ptilde[reverse of noising trajectory] for each pattern.

        This is a plain steepest-ascent loop on the analytic gradient. There is
        no backpropagation through time and no optimizer state: the source's
        rule is local and memoryless.

        normalize_by_steps -- the source (Eq. 8-9) SUMS the per-step gradient
        over the whole trajectory. Because that sum scales with the number of
        steps K, a learning rate calibrated at one trajectory length overshoots
        at another. Dividing by K is a learning-rate reparameterisation of the
        SAME ascent direction, not a different algorithm. The flag is reported
        with the result so a reader knows which variant produced the numbers.
        """
        g = torch.Generator(device="cpu").manual_seed(int(seed))
        history: List[float] = []
        for s in range(steps):
            acc_J = torch.zeros_like(self.J_raw)
            acc_b = torch.zeros_like(self.b)
            ep_logp = 0.0
            for t in range(n_traj_per_step):
                pat = patterns[(s * n_traj_per_step + t) % patterns.shape[0]]
                traj, _ = self.noise_trajectory(pat, generator=g)
                gj, gb = self.reverse_logprob_grad(traj)
                if normalize_by_steps:
                    k_steps = max(1, traj.shape[0] - 1)
                    gj = gj / k_steps
                    gb = gb / k_steps
                acc_J += gj
                acc_b += gb
                ep_logp += self.reverse_logprob(traj)
            with torch.no_grad():
                self.J_raw += alpha * acc_J / n_traj_per_step
                self.b += alpha * acc_b / n_traj_per_step
            history.append(ep_logp / n_traj_per_step)
            if verbose and (s % max(1, steps // 10) == 0):
                print(f"  [thermo] step {s:4d}  mean -ln Ptilde = {history[-1]:.4f}")
        return {"loss_first": history[0], "loss_last": history[-1],
                "n_steps": steps, "history": history,
                "normalize_by_steps": bool(normalize_by_steps)}

    def reverse_logprob(self, traj: torch.Tensor) -> float:
        """-ln Ptilde_theta(reverse trajectory), the source's loss (Eq. 7, summed)."""
        cfg = self.cfg
        x = traj[:-1]
        dx = traj[1:] - traj[:-1]
        xp = traj[1:]
        r = (-dx + cfg.mu * self.force(xp) * cfg.dt)
        return float((r ** 2).sum(dim=-1).mean() /
                     (4.0 * cfg.mu * cfg.kT * cfg.dt))

    @torch.no_grad()
    def mean_heat_emitted(self, patterns: torch.Tensor, n: int = 20,
                          seed: int = 0) -> float:
        """<Q> over generation trajectories: Q = V(x(0)) - V(x(t_f)).

        No work is done after the biases are established, so the potential-energy
        drop is the heat emitted (source, "Thermodynamic advantage").
        """
        g = torch.Generator(device="cpu").manual_seed(int(seed))
        qs = []
        for _ in range(n):
            x0 = self._cold_noise(g)
            x1 = x0.clone()
            for _ in range(self.cfg.n_steps):
                x1 = self.step(x1, bias=None, generator=g)
            qs.append(float(self.potential(x0) - self.potential(x1)))
        return sum(qs) / len(qs)

    @torch.no_grad()
    def _cold_noise(self, generator=None) -> torch.Tensor:
        cfg = self.cfg
        J_saved = self.J_raw.data.clone()
        self.J_raw.data.zero_()
        x = torch.zeros(cfg.n_units, device=self.device)
        for _ in range(int(0.5 / cfg.dt)):
            x = self.step(x, bias=None, generator=generator)
        self.J_raw.data.copy_(J_saved)
        return x

    def state_dict_memory(self) -> Dict[str, torch.Tensor]:
        """Serialisable coupling field. A thermodynamic computer's learned state
        is theta; if it is not serialised, 'learning' is amnesia on restart."""
        return {"J": self.effective_J().detach().cpu().clone(),
                "b": self.b.detach().cpu().clone()}

    def load_memory(self, mem: Dict[str, torch.Tensor]) -> None:
        J = mem["J"].to(self.device)
        with torch.no_grad():
            self.J_raw.copy_(0.5 * (J + J.t()))
            self.b.copy_(mem["b"].to(self.device))


# --------------------------------------------------------------- pre-registered
GATE_OVERLAP_GAIN = 0.20      # trained must beat the zero-coupling null arm
GATE_LOSS_DESCENT = 0.05      # relative drop in -ln Ptilde


@dataclass
class ThermoVerdict:
    verdict: str
    checks: Dict[str, bool] = field(default_factory=dict)
    measured: Dict[str, float] = field(default_factory=dict)


def run_thermodynamic_experiment(
    n_units: int = 48, n_visible: int = 16, train_steps: int = 200,
    n_traj_per_step: int = 4, alpha: float = 0.05, seed: int = 0,
    device: str = "cpu",
) -> ThermoVerdict:
    """Pre-registered test of the source's algorithm.

    ARMS
      trained   : couplings updated by the analytic rule (Eq. 8-11)
      null      : identical computer, couplings held at zero (the sampler itself)

    METRIC
      overlap(pattern) = normalised dot product between the generated VISIBLE
      slice and the nearest training pattern. Reported as the mean over held-out
      generation seeds. The null arm measures what the cold-noise initial
      condition alone achieves, so the gate cannot be passed by the sampler.
    """
    cfg = LangevinConfig(n_units=n_units, n_visible=n_visible)
    patterns = make_stripe_patterns(n_visible)

    torch.manual_seed(seed)
    model = LangevinComputer(cfg, seed=seed, device=device)
    before = model.reverse_logprob(model.noise_trajectory(patterns[0],
        generator=torch.Generator().manual_seed(seed))[0])
    train = model.train_on_patterns(patterns, steps=train_steps,
                                    n_traj_per_step=n_traj_per_step,
                                    alpha=alpha, seed=seed)

    def overlap_of(m: LangevinComputer, n: int = 24) -> float:
        g = torch.Generator(device="cpu").manual_seed(seed + 777)
        vals = []
        for _ in range(n):
            x = m.generate(generator=g)[:n_visible]
            xn = x / x.norm().clamp_min(1e-9)
            pn = patterns / patterns.norm(dim=-1, keepdim=True)
            vals.append(float((xn @ pn.t()).max()))
        return sum(vals) / len(vals)

    trained_overlap = overlap_of(model)
    null_model = LangevinComputer(cfg, seed=seed, device=device)  # couplings stay 0
    null_overlap = overlap_of(null_model)

    loss_ratio = (train["loss_first"] - train["loss_last"]) / max(
        abs(train["loss_first"]), 1e-12)
    checks = {
        "C1_loss_descent": bool(loss_ratio >= GATE_LOSS_DESCENT),
        "C2_beats_null": bool(trained_overlap - null_overlap >= GATE_OVERLAP_GAIN),
    }
    measured = {
        "overlap_trained": trained_overlap,
        "overlap_null": null_overlap,
        "overlap_gain": trained_overlap - null_overlap,
        "loss_first": train["loss_first"],
        "loss_last": train["loss_last"],
        "loss_relative_drop": loss_ratio,
        "gate_overlap_gain": GATE_OVERLAP_GAIN,
        "gate_loss_descent": GATE_LOSS_DESCENT,
    }
    if all(checks.values()):
        verdict = ("THERMODYNAMIC_LEARNING_ENGAGES -- the analytic reverse-trajectory "
                   "rule reduces -ln Ptilde and the trained coupling field generates "
                   "structure the zero-coupling sampler does not.")
    elif checks["C1_loss_descent"]:
        verdict = ("PARTIAL -- the objective descends but generation does not beat the "
                   "null sampler. The rule changes the computer without changing its "
                   "output distribution; not promotable.")
    else:
        verdict = ("FALSIFIED_THERMODYNAMIC_RULE -- the pre-registered objective did "
                   "not descend. The implementation does not implement the source.")
    return ThermoVerdict(verdict=verdict, checks=checks, measured=measured)


def _main() -> int:
    import argparse
    import json
    ap = argparse.ArgumentParser(description="HENRI thermodynamic learning experiment")
    ap.add_argument("--steps", type=int, default=200)
    ap.add_argument("--units", type=int, default=48)
    ap.add_argument("--alpha", type=float, default=0.05)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--out", default=None, help="write JSON receipt here")
    args = ap.parse_args()

    res = run_thermodynamic_experiment(
        n_units=args.units, train_steps=args.steps, alpha=args.alpha,
        seed=args.seed, device=args.device)
    payload = {"schema": "henri.thermo-langevin.v1",
               "source": "arXiv:2506.15121v3 (Whitelam, generative thermodynamic computing)",
               "device": args.device,
               "verdict": res.verdict, "checks": res.checks, "measured": res.measured}
    print(json.dumps(payload, indent=2))
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2)
    return 0 if all(res.checks.values()) else 1


if __name__ == "__main__":
    raise SystemExit(_main())
