"""
HENRI Architecture: Expected Free Energy (EFE) Latent Planner
Author: Aletheia
System State: Two-Wire Pragmatic/Epistemic Separation Active

This module evaluates candidate wave trajectories generated by the Swarm.
It strictly enforces the Free Energy Principle by decoupling Epistemic Surprise
(Sagnac Delta) from Pragmatic Value (Prior Preference Resonance).
"""

import torch
import torch.nn.functional as F

class ExpectedFreeEnergyPlanner:
    def __init__(self, sequence_dim: int = 4096, beta_pragmatic: float = 1.0):
        """
        Initializes the EFE Planner with a Hopfield preference store.
        
        Args:
            sequence_dim: Dimensionality of the complex unit hypersphere (S^4095).
            beta_pragmatic: The coupling constant (γ) controlling the influence 
                            of the pragmatic prior over the epistemic drive.
        """
        self.dim = sequence_dim
        self.beta = beta_pragmatic
        # The Hopfield store for favorable engrams. Empty until a successful trajectory is logged.
        self.preference_store = torch.empty((0, sequence_dim), dtype=torch.complex64)

    def register_successful_engram(self, predicted_wave: torch.Tensor):
        """
        Consolidates a successful prediction into the prior preference store.
        This forms the baseline for future pragmatic value calculations.
        """
        # Ensure the engram remains on the unit hypersphere
        normalized_wave = predicted_wave / torch.abs(predicted_wave).clamp(min=1e-12)
        self.preference_store = torch.cat([self.preference_store, normalized_wave.unsqueeze(0).detach()], dim=0)

    def compute_pragmatic_value(self, candidate_wave: torch.Tensor) -> torch.Tensor:
        """
        Computes p(o|m) = exp(V(s)). The pragmatic value is the maximum phase resonance 
        (cosine similarity in the complex domain) against the preference store.
        """
        if self.preference_store.size(0) == 0:
            return torch.zeros(candidate_wave.size(0), device=candidate_wave.device)
            
        # Compute normalized inner product (phase coherence) across the store
        # Real component of complex inner product yields cosine of phase difference
        resonance_matrix = torch.matmul(candidate_wave, self.preference_store.conj().T).real
        max_resonance, _ = torch.max(resonance_matrix, dim=-1)
        return max_resonance

    def evaluate_trajectory_fitness(self, candidate_wave: torch.Tensor, boundary_axiom: torch.Tensor) -> torch.Tensor:
        """
        Evaluates the Expected Free Energy (EFE) of a candidate trajectory.
        Lower EFE indicates a more thermodynamically favorable path.
        
        G = Epistemic_Surprise - β * Pragmatic_Value
        """
        # 1. Epistemic Surprise (Sagnac Delta): 1.0 - phase coherence with target boundary
        epistemic_coherence = torch.sum(candidate_wave * boundary_axiom.conj(), dim=-1).real
        epistemic_surprise = 1.0 - epistemic_coherence
        
        # 2. Pragmatic Value: Resonance with previously successful engrams
        pragmatic_value = self.compute_pragmatic_value(candidate_wave)
        
        # 3. Total Expected Free Energy
        expected_free_energy = epistemic_surprise - (self.beta * pragmatic_value)
        
        return expected_free_energy