import torch
import torch.nn as nn
import torch.nn.functional as F
import math

class StiefelManifoldProjector:
    """
    Enforces the Stiefel manifold invariant (W^T W = I) using high-order 
    Newton-Schulz orthogonalization. This prevents semantic causal leakage 
    and maintains the unit modulus of the information vectors.
    """
    @staticmethod
    @torch.no_grad()
    def bjorck_newton_orthonormalize(weight_matrix: torch.Tensor, iterations: int = 5, eps: float = 1e-7) -> torch.Tensor:
        W = weight_matrix.clone()
        
        # Initial operator scaling bound
        norm_val = torch.norm(W, p=2)
        if norm_val > 1.0 + eps:
            W.div_(norm_val)

        # Iterative Newton-Schulz polynomial mapping: W_{k+1} = 1.5W_k - 0.5W_k(W_k^T W_k)
        for _ in range(iterations):
            WTW = torch.matmul(W.t().conj(), W)
            W = 1.5 * W - 0.5 * torch.matmul(W, WTW)
            
        return W

class HolographicVectorLifter(nn.Module):
    """
    The Epistemic Transducer.
    Translates discrete multi-modal structures (ASTs, logical grids, raw strings)
    directly into Fourier Holographic Reduced Representations (FHRRs) on S^{4095}.
    """
    def __init__(self, vocab_size: int, dim: int = 4096):
        super().__init__()
        self.dim = dim
        self.vocab_size = vocab_size
        
        # Initialize the base lexicon as continuous phase angles rather than scalar weights.
        # \theta \in [0, 2\pi)
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        raw_phases = torch.empty(vocab_size, dim, device=device).uniform_(0, 2 * math.pi)
        
        # Project initial real-valued topology to the Stiefel manifold to ensure baseline orthogonality
        orthogonal_phases = StiefelManifoldProjector.bjorck_newton_orthonormalize(raw_phases)
        
        # Lock parameters as unit-magnitude complex phasors: \Psi = e^{j\theta}
        self.phase_lexicon = nn.Parameter(torch.polar(torch.ones_like(orthogonal_phases), orthogonal_phases))

    @torch.no_grad()
    def project_to_unit_modulus(self):
        """
        Forces the amplitudes of the entire complex lexicon back to exactly 1.0,
        preserving the learned continuous phase angle generated by AdamW.
        """
        self.phase_lexicon.copy_(torch.polar(torch.ones_like(self.phase_lexicon.real), self.phase_lexicon.angle()))

    def _retrieve_phasor(self, indices: torch.Tensor) -> torch.Tensor:
        """Extracts the complex phasor representation for the given structural primitives."""
        return self.phase_lexicon[indices]

    def bind_fhrr(self, phasor_a: torch.Tensor, phasor_b: torch.Tensor) -> torch.Tensor:
        """
        Executes spatial circular convolution in the frequency domain.
        For FHRRs, this simplifies natively to element-wise complex multiplication (\odot).
        """
        return phasor_a * phasor_b

    def bundle_superposition(self, bound_phasors: torch.Tensor, dim_reduce: int = 1) -> torch.Tensor:
        """
        Aggregates multiple bound representations via linear superposition.
        """
        return torch.sum(bound_phasors, dim=dim_reduce)

    def inject_langevin_heat(self, wavefront: torch.Tensor, temperature: float) -> torch.Tensor:
        """
        Injects controlled stochastic thermal variance (Langevin Heat).
        This shakes the continuous wavefront out of sub-optimal local minima prior to 
        BTO phase mask transmission, preventing premature Logic Locks.
        """
        if temperature <= 0.0:
            return wavefront
            
        # Generate Gaussian noise wrapped to the phase domain
        thermal_noise_phase = torch.empty_like(wavefront.real).normal_(mean=0.0, std=temperature)
        thermal_phasor = torch.polar(torch.ones_like(thermal_noise_phase), thermal_noise_phase)
        
        # Diffract the wavefront using the thermal variance
        return wavefront * thermal_phasor

    def forward(self, structural_nodes: torch.Tensor, relational_edges: torch.Tensor = None, heat: float = 0.0) -> torch.Tensor:
        """
        Lifts an arbitrary relational graph (e.g., AST node -> connection -> child node)
        into a unified, pristine complex wavefront ready for the BTO optical core.
        
        Args:
            structural_nodes: [Batch, Sequence] discrete indices.
            relational_edges: [Batch, Sequence] discrete relationship indices. If None, assumes flat sequence.
            heat: Langevin thermostat scalar to perturb stagnant trajectories.
        """
        # 1. Map to complex invariant unit-phasors
        psi_nodes = self._retrieve_phasor(structural_nodes)
        
        if relational_edges is not None:
            psi_edges = self._retrieve_phasor(relational_edges)
            # 2. Bind structure to relations (Circular Convolution)
            psi_bound = self.bind_fhrr(psi_nodes, psi_edges)
        else:
            # If flat sequence, structural nodes form their own boundaries
            psi_bound = psi_nodes
        
        # 3. Bundle into a singular dense global representation
        psi_bundled = self.bundle_superposition(psi_bound, dim_reduce=1)
        
        # 4. Inject physical thermodynamic variance if required
        psi_heated = self.inject_langevin_heat(psi_bundled, temperature=heat)
        
        # 5. The Hypersphere Clamp: L2 Normalize back to S^{4095}
        # Ensures unit modulus is strictly conserved for Pockels effect lithography
        psi_final = F.normalize(psi_heated, p=2, dim=-1)
        
        return psi_final